### ISSUE TITLE
Mouse data

### ISSUE THREAD

**Issue by peterkilfeather** [tkamath1/Kamathetal2022#1]
Hi there,
Are the mouse data & clustering labels available publicly yet?
Thank you. Lovely paper!

**Comment by tkamath1** [comment]
Hey Peter:

Thanks for your message. We didn't upload the mouse data during preprint stage as the data was generated via the BICCN consortium and thus would be deposited on NeMO. 

I think we're still waiting for that work to come out; in the meantime, if you provide your email, I'm happy to send over the .mtx files and clustering labels of the mouse data used for the species integrative analysis in the paper.

**Comment by peterkilfeather** [comment]
Thank you, have emailed you.
