### ISSUE TITLE
human data object available ?

### ISSUE THREAD

**Issue by deevdevil88** [tkamath1/Kamathetal2022#2]
Hi , 
First of all. This is a really nice paper. I read the pre-print last summer and really enjoyed it and been waiting for the final paper to be published.
I was wondering if the Human NR4A2 positive dataset , for all cell-types and just the DaN subtypes was available as a seurat/single cell or ann data or even a liger object?

I wanted to use it as a reference for a project and thought to ask if you would be happy to provide a processed final object for that? i know the filtered mtx files and the umap co-ordinates and the metadata are on SCP , i just wondered if you would be happy to share the final object. Would help me save some time.
Also while im on here, is also possible to ask about the mouse data used in the cross -species analysis? is is possible to get the mtx and metadata and UMAP for that as well?

Best,
Devika

**Comment by tkamath1** [comment]
Hi Devika:

Thanks for your kind words. Of course! Happy to provide the NR4A2+ object and the DaN subtypes as liger objects. Would also be happy to share the mouse data. Could you drop me an email at the email address listed on the README of this repo? I'll be able to respond and share with you all of those objects this coming week.

**Comment by deevdevil88** [comment]
Hi Tushar,
Thank you for the quick reply. I have emailed you regarding this.

Best,
Devika

**Comment by tkamath1** [comment]
Closing this issue -- resolved.
