### ISSUE TITLE
Read10X(GSE178265_Homo_matrix.mtx.gz) takes too long and need lots of RAM! 

### ISSUE THREAD

**Issue by behyag** [tkamath1/Kamathetal2022#3]
hi, 

first of all, I really enjoyed reading the paper! great work! 
I have downloaded the human count matrix (4.7 GB) which I assume is the combined for all 380K nuclei, plus the features and barcodes tsv files from GEO. Trying to load with Read10x() but requires lots of RAM! is it possible to have matrixes for individual human samples? I guess a formal application is in order, right?  any suggestions and advice would be highly appreciated! 

best, 
/Behzad

**Comment by JZL** [comment]
Hi,

I can try to get to this later but I don't want to hold you up.

I recommend using google colab (free, can [even use R](https://colab.research.google.com/notebook#create=true&language=r)) or a google cloud ubuntu instance (free for a number of hours under google's free tie + $300 starting bonus, even if you request a machine with hundreds of GB of ram ) to boot up a machine with more RAM so you can load it in

**Comment by tkamath1** [comment]
Closing this issue now
